// Build-time source code extraction.
// Reads the .tsx source of each registry component/block at build time and
// emits a TypeScript file with the contents as string literals. This avoids
// runtime fs.readFileSync, which fails in serverless deployments where the
// registry source files aren't in the deployed bundle.
//
// Run via `prebuild` in apps/web/package.json.

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(HERE, "..", "..", "..")
const REGISTRY_SRC = join(REPO_ROOT, "packages", "registry", "src")
const OUT = join(HERE, "..", "lib", "registry", "sources.generated.ts")

function readSource(relativePath) {
  return readFileSync(join(REGISTRY_SRC, relativePath), "utf-8")
}

function collectSources(subdir) {
  const dir = join(REGISTRY_SRC, subdir)
  try {
    return Object.fromEntries(
      readdirSync(dir)
        .filter((name) => statSync(join(dir, name)).isDirectory())
        .map((name) => [name, readSource(`${subdir}/${name}/index.tsx`)]),
    )
  } catch {
    return {}
  }
}

const components = collectSources("components")
const blocks = collectSources("blocks")

const content = `// AUTO-GENERATED by scripts/build-sources.mjs — do not edit.
// Source code is read from packages/registry/src/** at build time and
// inlined here so the bundle is self-contained (no runtime fs reads).

export const SOURCES = {
  components: ${JSON.stringify(components, null, 2)},
  blocks: ${JSON.stringify(blocks, null, 2)},
} as const
`

writeFileSync(OUT, content, "utf-8")
console.log(
  `[build-sources] wrote ${OUT} (${Object.keys(components).length} components, ${Object.keys(blocks).length} blocks)`,
)