// AUTO-GENERATED by scripts/build-sources.mjs — do not edit.
// Source code is read from packages/registry/src/** at build time and
// inlined here so the bundle is self-contained (no runtime fs reads).

export const SOURCES = {
  components: {
  "button": "\"use client\"\n\nimport { Button as ShadcnButton } from \"@workspace/ui/components/button\"\n\nexport type ButtonProps = React.ComponentProps<typeof ShadcnButton>\n\nexport { ShadcnButton as Button }\n\nexport function ButtonDemo() {\n  return (\n    <div className=\"flex flex-wrap items-center gap-2\">\n      <ShadcnButton variant=\"default\">Default</ShadcnButton>\n      <ShadcnButton variant=\"secondary\">Secondary</ShadcnButton>\n      <ShadcnButton variant=\"outline\">Outline</ShadcnButton>\n      <ShadcnButton variant=\"ghost\">Ghost</ShadcnButton>\n      <ShadcnButton variant=\"destructive\">Destructive</ShadcnButton>\n    </div>\n  )\n}",
  "icon-button": "\"use client\"\n\nimport { Button as ShadcnButton } from \"@workspace/ui/components/button\"\nimport { cn } from \"@workspace/ui/lib/utils\"\n\nexport interface IconButtonProps\n  extends Omit<React.ComponentProps<typeof ShadcnButton>, \"children\" | \"size\"> {\n  \"aria-label\": string\n  children: React.ReactNode\n  size?: \"sm\" | \"md\" | \"lg\"\n}\n\nconst SIZE_CLASSES: Record<NonNullable<IconButtonProps[\"size\"]>, string> = {\n  sm: \"size-8\",\n  md: \"size-10\",\n  lg: \"size-12\",\n}\n\nexport function IconButton({\n  className,\n  size = \"md\",\n  type = \"button\",\n  ...props\n}: IconButtonProps) {\n  return (\n    <ShadcnButton\n      type={type}\n      size=\"icon\"\n      className={cn(SIZE_CLASSES[size], className)}\n      {...props}\n    />\n  )\n}\n\nexport function IconButtonDemo() {\n  return (\n    <div className=\"flex flex-wrap items-center gap-2\">\n      <IconButton aria-label=\"Add\" size=\"sm\">\n        +\n      </IconButton>\n      <IconButton aria-label=\"Edit\" size=\"md\">\n        ✎\n      </IconButton>\n      <IconButton aria-label=\"Delete\" size=\"lg\">\n        ×\n      </IconButton>\n    </div>\n  )\n}"
},
  blocks: {},
} as const
